bingoGenerator = require("./generators/generator_bases/isaac_generator.js");

var bingoList = [];

var easyChallenges = [
  { name: "Westopolis 5 Keys", types: ["westopolis", "keys"] },
  { name: "Digital Circuit 5 Keys", types: ["digitalcircuit", "keys"] },
  { name: "Glyphic Canyon 5 Keys", types: ["glyphiccanyon", "keys"] },
  { name: "Lethal Highway 5 Keys", types: ["lethalhighway", "keys"] },
  { name: "Cryptic Castle 5 Keys", types: ["crypticcastle", "keys"] },
  { name: "Prison Island 5 Keys", types: ["prisonisland", "keys"] },
  { name: "Circus Park 5 Keys", types: ["circuspark", "keys"] },
  { name: "Westopolis DNH", types: ["westopolis", "dnh"] },
  { name: "Digital Circuit DH", types: ["digitalcircuit", "dnh"] },
  { name: "Glyphic Canyon DNH", types: ["glyphiccanyon", "dnh"] },
  { name: "Lethal Highway DH", types: ["lethalhighway", "dnh"] },
  { name: "Cryptic Castle DNH", types: ["crypticcastle", "dnh"] },
  { name: "Prison Island DNH", types: ["prisonisland", "dnh"] },
  { name: "Circus Park DNH", types: ["circuspark", "dnh"] },
  { name: "Westopolis 1 Shadow Box & finish", types: ["westopolis", "box"] },
  { name: "Digital Circuit 2 Shadow Boxes & finish", types: ["digitalcircuit", "box"] },
  { name: "Glyphic Canyon 4 Shadow Boxes & finish", types: ["glyphiccanyon", "box"] },
  { name: "Lethal Highway 5 Shadow Boxes & finish", types: ["lethalhighway", "box"] },
  { name: "Cryptic Castle 3 Shadow Boxes & finish", types: ["crypticcastle", "box"] },
  { name: "Prison Island 3 Shadow Boxes & finish", types: ["prisonisland", "box"] },
  { name: "Circus Park 2 Shadow Boxes & finish", types: ["circuspark", "box"] },
  { name: "Westopolis Neutral w/o Chaos Control", types: ["westopolis", "restricted"] },
  { name: "Westopolis Hero w/o Chaos Control", types: ["westopolis", "restricted"] },
  { name: "Glyphic Canyon Dark w/o Chaos Control", types: ["glyphiccanyon", "restricted"] },
  { name: "Glyphic Canyon Neutral w/o Chaos Control", types: ["glyphiccanyon", "restricted"] },
  { name: "Glyphic Canyon Hero w/o Chaos Control", types: ["glyphiccanyon", "restricted"] },
  { name: "Lethal Highway Dark w/o Chaos Control", types: ["lethalhighway", "restricted"] },
  { name: "Prison Island Dark w/o Chaos Control", types: ["prisonisland", "restricted"] },
  { name: "Prison Island Neutral w/o Chaos Control", types: ["prisonisland", "restricted"] },
  { name: "Prison Island Hero w/o Chaos Control", types: ["prisonisland", "restricted"] },
  { name: "Circus Park Dark w/o Chaos Control", types: ["circuspark", "restricted"] },
  { name: "Circus Park Neutral w/o Chaos Control", types: ["circuspark", "restricted"] },
  { name: "Circus Park Hero w/o Chaos Control", types: ["circuspark", "restricted"] },
  { name: "Westopolis Dark via all 6 checkpoints", types: ["westopolis", "checkpoints"] },
  { name: "Westopolis Neutral via all 6 checkpoints", types: ["westopolis", "checkpoints"] },
  { name: "Westopolis Hero via all 6 checkpoints", types: ["westopolis", "checkpoints"] },
  { name: "Digital Circuit Dark via all 7 checkpoints", types: ["digitalcircuit", "checkpoints"] },
  { name: "Digital Circuit Hero via all 7 checkpoints", types: ["digitalcircuit", "checkpoints"] },
  { name: "Glyphic Canyon Dark via all 8 checkpoints", types: ["glyphiccanyon", "checkpoints"] },
  { name: "Glyphic Canyon Neutral via all 8 checkpoints", types: ["glyphiccanyon", "checkpoints"] },
  { name: "Glyphic Canyon Hero via all 8 checkpoints", types: ["glyphiccanyon", "checkpoints"] },
  { name: "Lethal Highway Dark via all 5 checkpoints", types: ["lethalhighway", "checkpoints"] },
  { name: "Lethal Highway Hero via all 5 checkpoints", types: ["lethalhighway", "checkpoints"] },
  { name: "Cryptic Castle Dark via all 8 checkpoints", types: ["crypticcastle", "checkpoints"] },
  { name: "Cryptic Castle Neutral via all 8 checkpoints", types: ["crypticcastle", "checkpoints"] },
  { name: "Cryptic Castle Hero via all 8 checkpoints", types: ["crypticcastle", "checkpoints"] },
  { name: "Prison Island Dark via all 7 checkpoints", types: ["prisonisland", "checkpoints"] },
  { name: "Prison Island Neutral via all 7 checkpoints", types: ["prisonisland", "checkpoints"] },
  { name: "Prison Island Hero via all 7 checkpoints", types: ["prisonisland", "checkpoints"] },
  { name: "Circus Park Dark via all 7 checkpoints", types: ["circuspark", "checkpoints"] },
  { name: "Circus Park Neutral via all 7 checkpoints", types: ["circuspark", "checkpoints"] },
  { name: "Circus Park Hero via all 7 checkpoints", types: ["circuspark", "checkpoints"] },
  { name: "Defeat Black Bull w/o Chaos Control", types: ["blackbull", "restricted"] },
  { name: "Defeat Black Bull without Guns", types: ["blackbull", "restricted"] },
  { name: "Defeat Egg Breaker without Guns", types: ["eggbreaker", "restricted"] },
  { name: "10 Keys", types: ["keys"] },
  { name: "25 Keys", types: ["keys"] },
  { name: "10 A Ranks", types: ["abc"] },
  { name: "25 A Ranks", types: ["abc"] },
  { name: "Die to a Gold Beetle", types: ["goldbeetle"] },
  { name: "Collect 88 Rings in 2P Game Level 3", types: ["2pgame", "box"] },
  { name: "Collect 64 Rings in 2P Game Level 1", types: ["2pgame", "box"] },
  { name: "Collect 50 Rings in 2P Game Level 2", types: ["2pgame", "box"] },
  { name: "Ride the Armored Vehicle to the 5th Checkpoint (Westopolis)", types: ["westopolis", "box"] },
  { name: "Finish Westopolis Hero or Dark with 100+ Road Signs", types: ["westopolis", "box"] },
  { name: "Flip Over 2 Trucks (Westopolis)", types: ["westopolis", "box"] },
  { name: "Defeat 44 Black Arms OR 34 GUN Soldiers then Westopolis Neutral", types: ["westopolis", "restricted"] },
  { name: "Hit 4 Capsules (Westopolis)", types: ["westopolis", "box"] },
  { name: "Hit 2 Life Capsules in Westopolis", types: ["westopolis", "box"] },
  { name: "Hit a Life Capsule in Digital Circuit", types: ["digitalcircuit", "box"] },
  { name: "Glyphic Canyon Hero with a higher Dark Score", types: ["glyphiccanyon", "restricted"] },
  { name: "Glyphic Canyon Dark Pacifist", types: ["glyphiccanyon", "restricted"] },
  { name: "Lethal Highway Dark Pacifist", types: ["lethalhighway", "restricted"] },
  { name: "Lethal Highway Hero with NO Capsules", types: ["lethalhighway", "restricted"] },
  { name: "Lethal Highway Dark with NO Capsules", types: ["lethalhighway", "restricted"] },
  { name: "Save Cheese then Cream (Cryptic Castle)", types: ["crypticcastle", "restricted"] },
  { name: "Prison Island Hero Pacifist", types: ["prisonisland", "restricted"] },
  { name: "39 GUN Soldiers in Prison Island Hero", types: ["prisonisland", "restricted"] },
  { name: "Hit a Flame Shield Capsule in Prison Island", types: ["prisonisland", "box"] },
  { name: "Circus Park Neutral with 399 rings", types: ["circuspark", "restricted"] },
  { name: "10 Keys OR 5 A Ranks", types: ["or", "keys", "abc"] },
  { name: "5 Keys in Westopolis OR 2 Keys in Stage 3", types: ["or"] },
  { name: "Finish a stage with 500+ ammo", types: ["box"] },
  { name: "Finish a stage with 100+ special weapon ammo", types: ["box"] },
  { name: "Finish a stage with 50+ special weapon ammo", types: ["box"] },
  { name: "Have a 20+ Life Counter", types: ["box"] },
  { name: "Waste both meters in one stage (stand still, don't shoot)", types: ["restricted"] },
  { name: "Defeat a Black Oak w/ only an Egg Bazooka", types: ["restricted"] },
  { name: "Defeat a Big Foot w/ only homing attacks", types: ["restricted"] },
  { name: "Defeat a Sand Worm w/ only a Melee Weapon", types: ["restricted"] },
  { name: "Heal a Gold Beetle", types: ["goldbeetle"] },
  { name: "Defeat a Shadow Android w/ only spindashes", types: ["restricted"] },
  { name: "Defeat 10 enemies w/ a Chaos Control", types: ["restricted"] },
  { name: "360 No Scope a GUN Soldier", types: ["restricted"] }
];

bingoList[1] = easyChallenges;


var mediumChallenges = [
  { name: "Central City 5 Keys", types: ["centralcity", "keys"] },
  { name: "The Doom 5 Keys", types: ["thedoom", "keys"] },
  { name: "Sky Troops 5 Keys", types: ["skytroops", "keys"] },
  { name: "Mad Matrix 5 Keys", types: ["madmatrix", "keys"] },
  { name: "Death Ruins 5 Keys", types: ["deathruins", "keys"] },
  { name: "The ARK 5 Keys", types: ["theark", "keys"] },
  { name: "Air Fleet 5 Keys", types: ["airfleet", "keys"] },
  { name: "Iron Jungle 5 Keys", types: ["ironjungle", "keys"] },
  { name: "Space Gadget 5 Keys", types: ["spacegadget", "keys"] },
  { name: "Lost Impact 5 Keys", types: ["lostimpact", "keys"] },
  { name: "Central City DH", types: ["centralcity", "dnh"] },
  { name: "The Doom DNH", types: ["thedoom", "dnh"] },
  { name: "Sky Troops DNH", types: ["skytroops", "dnh"] },
  { name: "Mad Matrix DNH", types: ["madmatrix", "dnh"] },
  { name: "Death Ruins DH", types: ["deathruins", "dnh"] },
  { name: "The ARK DN", types: ["theark", "dnh"] },
  { name: "Air Fleet DNH", types: ["airfleet", "dnh"] },
  { name: "Iron Jungle DNH", types: ["ironjungle", "dnh"] },
  { name: "Space Gadget DNH", types: ["spacegadget", "dnh"] },
  { name: "Lost Impact NH", types: ["lostimpact", "dnh"] },
  { name: "Central City 2 Shadow Boxes & finish", types: ["centralcity", "box"] },
  { name: "The Doom 3 Shadow Boxes & finish", types: ["thedoom", "box"] },
  { name: "Sky Troops 4 Shadow Boxes & finish", types: ["skytroops", "box"] },
  { name: "Mad Matrix 3 Shadow Boxes & finish", types: ["madmatrix", "box"] },
  { name: "Death Ruins 2 Shadow Boxes & finish", types: ["deathruins", "box"] },
  { name: "The ARK 2 Shadow Boxes & finish", types: ["theark", "box"] },
  { name: "Air Fleet 6 Shadow Boxes & finish", types: ["airfleet", "box"] },
  { name: "Iron Jungle 3 Shadow Boxes & finish", types: ["ironjungle", "box"] },
  { name: "Space Gadget 1 Shadow Box & finish", types: ["spacegadget", "box"] },
  { name: "Lost Impact 1 Shadow Box & finish", types: ["lostimpact", "box"] },
  { name: "The Doom Neutral w/o Chaos Control", types: ["thedoom", "restricted"] },
  { name: "The Doom Hero w/o Chaos Control", types: ["thedoom", "restricted"] },
  { name: "Sky Troops Dark w/o Chaos Control", types: ["skytroops", "restricted"] },
  { name: "Sky Troops Neutral w/o Chaos Control", types: ["skytroops", "restricted"] },
  { name: "Sky Troops Hero w/o Chaos Control", types: ["skytroops", "restricted"] },
  { name: "Mad Matrix Hero w/o Chaos Control", types: ["madmatrix", "restricted"] },
  { name: "Death Ruins Dark w/o Chaos Control", types: ["deathruins", "restricted"] },
  { name: "Air Fleet Neutral w/o Chaos Control", types: ["airfleet", "restricted"] },
  { name: "Air Fleet Hero w/o Chaos Control", types: ["airfleet", "restricted"] },
  { name: "Iron Jungle Dark w/o Chaos Control", types: ["ironjungle", "restricted"] },
  { name: "Iron Jungle Neutral w/o Chaos Control", types: ["ironjungle", "restricted"] },
  { name: "Space Gadget Dark w/o Chaos Control", types: ["spacegadget", "restricted"] },
  { name: "Space Gadget Neutral w/o Chaos Control", types: ["spacegadget", "restricted"] },
  { name: "Space Gadget Hero w/o Chaos Control", types: ["spacegadget", "restricted"] },
  { name: "Lost Impact Neutral w/o Chaos Control", types: ["lostimpact", "restricted"] },
  { name: "Lost Impact Hero w/o Chaos Control", types: ["lostimpact", "restricted"] },
  { name: "Central City Dark via all 6 checkpoints", types: ["centralcity", "checkpoints"] },
  { name: "Central City Hero via all 6 checkpoints", types: ["centralcity", "checkpoints"] },
  { name: "The Doom Dark via all 6 checkpoints", types: ["thedoom", "checkpoints"] },
  { name: "The Doom Neutral via all 6 checkpoints", types: ["thedoom", "checkpoints"] },
  { name: "The Doom Hero via all 6 checkpoints", types: ["thedoom", "checkpoints"] },
  { name: "Sky Troops Dark via all 8 checkpoints", types: ["skytroops", "checkpoints"] },
  { name: "Sky Troops Neutral via all 8 checkpoints", types: ["skytroops", "checkpoints"] },
  { name: "Sky Troops Hero via all 8 checkpoints", types: ["skytroops", "checkpoints"] },
  { name: "Mad Matrix Dark via all 6 checkpoints", types: ["madmatrix", "checkpoints"] },
  { name: "Mad Matrix Neutral via all 6 checkpoints", types: ["madmatrix", "checkpoints"] },
  { name: "Mad Matrix Hero via all 6 checkpoints", types: ["madmatrix", "checkpoints"] },
  { name: "Death Ruins Dark via all 7 checkpoints", types: ["deathruins", "checkpoints"] },
  { name: "Death Ruins Hero via all 7 checkpoints", types: ["deathruins", "checkpoints"] },
  { name: "The ARK Dark via all 8 checkpoints", types: ["theark", "checkpoints"] },
  { name: "The ARK Neutral via all 8 checkpoints", types: ["theark", "checkpoints"] },
  { name: "Air Fleet Dark via first 7 checkpoints", types: ["airfleet", "checkpoints"] },
  { name: "Air Fleet Neutral via all 8 checkpoints", types: ["airfleet", "checkpoints"] },
  { name: "Air Fleet Hero via all 8 checkpoints", types: ["airfleet", "checkpoints"] },
  { name: "Iron Jungle Dark via all 8 checkpoints", types: ["ironjungle", "checkpoints"] },
  { name: "Iron Jungle Neutral via all 8 checkpoints", types: ["ironjungle", "checkpoints"] },
  { name: "Iron Jungle Hero via first 7 checkpoints", types: ["ironjungle", "checkpoints"] },
  { name: "Space Gadget Dark via all 8 checkpoints", types: ["spacegadget", "checkpoints"] },
  { name: "Space Gadget Neutral via all 8 checkpoints", types: ["spacegadget", "checkpoints"] },
  { name: "Disable 5 Defense Shields in Space Gadget Hero", types: ["spacegadget", "restricted"] },
  { name: "Lost Impact Neutral via all 8 checkpoints", types: ["lostimpact", "checkpoints"] },
  { name: "Lost Impact Hero via all 8 checkpoints", types: ["lostimpact", "checkpoints"] },
  { name: "Air Fleet Dark Deathless", types: ["airfleet", "restricted"] },
  { name: "Iron Jungle Hero Deathless", types: ["ironjungle", "restricted"] },
  { name: "Defeat Both Black Bulls", types: ["and"] },
  { name: "Defeat Both Heavy Dog & Blue Falcon", types: ["and"] },
  { name: "3 Gold Beetles", types: ["goldbeetle"] },
  { name: "5 Gold Beetles", types: ["goldbeetle"] },
  { name: "7 Gold Beetles", types: ["goldbeetle"] },
  { name: "Defeat Heavy Dog without Guns", types: ["heavydog", "restricted"] },
  { name: "Defeat Blue Falcon without Guns", types: ["bluefalcon", "restricted"] },
  { name: "Unlock Westopolis & Central City", types: ["and"] },
  { name: "Unlock Digital Circuit & Mad Matrix", types: ["and"] },
  { name: "Unlock Glyphic Canyon & Sky Troops", types: ["and"] },
  { name: "Unlock Prison Island & Iron Jungle", types: ["and"] },
  { name: "Unlock Lethal Highway & Air Fleet", types: ["and"] },
  { name: "Unlock Cryptic Castle & Circus Park", types: ["and"] },
  { name: "Central City Dark with 19 small bombs removed", types: ["centralcity", "restricted"] },
  { name: "Find a Chaos Control Orb in Central City", types: ["centralcity", "box"] },
  { name: "Hit 11 Capsules (The Doom)", types: ["thedoom", "box"] },
  { name: "Hit 3 Life Capsules (The Doom)", types: ["thedoom", "box"] },
  { name: "Use 6 Dash Rings (The Doom)", types: ["thedoom", "keys"] },
  { name: "Activate Yellow & Green Tower in Mad Matrix Neutral", types: ["madmatrix", "restricted"] },
  { name: "Hit 4 Life Capsules (Death Ruins)", types: ["deathruins", "box"] },
  { name: "Finish The ARK w/ 100+ Rings", types: ["theark", "box"] },
  { name: "Fail Air Fleet Dark then do Hero", types: ["airfleet", "restricted"] },
  { name: "Defeat 34 Black Arms in Air Fleet Dark", types: ["airfleet", "restricted"] },
  { name: "Finish Iron Jungle w/ 100+ Tripod Ammo", types: ["ironjungle", "box"] },
  { name: "Hit 1 Life Capsule (Space Gadget)", types: ["spacegadget", "box"] },
  { name: "Finish Space Gadget w/ 200+ Rings", types: ["spacegadget", "box"] },
  { name: "Finish Lost Impact w/ 300+ Rings", types: ["lostimpact", "box"] },
  { name: "Hit 2 Life Capsules (Lost Impact)", types: ["lostimpact", "box"] }
];

bingoList[2] = mediumChallenges;


var hardChallenges = [
  { name: "GUN Fortress 5 Keys", types: ["gunfortress", "keys"] },
  { name: "Black Comet 5 Keys", types: ["blackcomet", "keys"] },
  { name: "Lava Shelter 5 Keys", types: ["lavashelter", "keys"] },
  { name: "Cosmic Fall 5 Keys", types: ["cosmicfall", "keys"] },
  { name: "Final Haunt 5 Keys", types: ["finalhaunt", "keys"] },
  { name: "GUN Fortress DH", types: ["gunfortress", "dnh"] },
  { name: "Black Comet DH", types: ["blackcomet", "dnh"] },
  { name: "Lava Shelter DH", types: ["lavashelter", "dnh"] },
  { name: "Cosmic Fall DH", types: ["cosmicfall", "dnh"] },
  { name: "Final Haunt DH", types: ["finalhaunt", "dnh"] },
  { name: "GUN Fortress 2 Shadow Boxes & finish", types: ["gunfortress", "box"] },
  { name: "Black Comet 5 Shadow Boxes & finish", types: ["blackcomet", "box"] },
  { name: "Lava Shelter 3 Shadow Boxes & finish", types: ["lavashelter", "box"] },
  { name: "Cosmic Fall 2 Shadow Boxes & finish", types: ["cosmicfall", "box"] },
  { name: "Final Haunt 3 Shadow Boxes & finish", types: ["finalhaunt", "box"] },
  { name: "GUN Fortress Hero w/o Chaos Control", types: ["gunfortress", "restricted"] },
  { name: "Black Comet Hero w/o Chaos Control", types: ["blackcomet", "restricted"] },
  { name: "Lava Shelter Dark w/o Chaos Control", types: ["lavashelter", "restricted"] },
  { name: "Lava Shelter Hero w/o Chaos Control", types: ["lavashelter", "restricted"] },
  { name: "Cosmic Fall Dark w/o Chaos Control", types: ["cosmicfall", "restricted"] },
  { name: "Cosmic Fall Hero w/o Chaos Control", types: ["cosmicfall", "restricted"] },
  { name: "Final Haunt Dark w/o Chaos Control", types: ["finalhaunt", "restricted"] },
  { name: "Final Haunt Hero w/o Chaos Control", types: ["finalhaunt", "restricted"] },
  { name: "GUN Fortress Dark via all 7 checkpoints", types: ["gunfortress", "checkpoints"] },
  { name: "GUN Fortress Hero via all 7 checkpoints", types: ["gunfortress", "checkpoints"] },
  { name: "Black Comet Dark via all 8 checkpoints", types: ["blackcomet", "checkpoints"] },
  { name: "Black Comet Hero via all 8 checkpoints", types: ["blackcomet", "checkpoints"] },
  { name: "Lava Shelter Dark via all 8 checkpoints", types: ["lavashelter", "checkpoints"] },
  { name: "Lava Shelter Hero via all 8 checkpoints", types: ["lavashelter", "checkpoints"] },
  { name: "Cosmic Fall Dark via all 7 checkpoints", types: ["cosmicfall", "checkpoints"] },
  { name: "Cosmic Fall Hero via all 7 checkpoints", types: ["cosmicfall", "checkpoints"] },
  { name: "Final Haunt Dark via all 8 checkpoints", types: ["finalhaunt", "checkpoints"] },
  { name: "Final Haunt Hero via all 8 checkpoints", types: ["finalhaunt", "checkpoints"] },
  { name: "All three Chaotix Missions (Team Combined)", types: ["and"] },
  { name: "All four Sonic Missions (Team Combined)", types: ["and"] },
  { name: "All 11 Gold Beetles (Team Combined)", types: ["goldbeetle"] },
  { name: "Defeat Sonic & Diablon without Guns", types: ["sonic&diablon", "restricted"] },
  { name: "Defeat Egg Dealer without Guns", types: ["eggdealer", "restricted"] },
  { name: "Defeat Black Doom without Guns", types: ["blackdoom", "restricted"] },
  { name: "Unlock The ARK & Cosmic Fall (Team Combined)", types: ["and"] },
  { name: "Unlock The Doom & Lost Impact (Team Combined)", types: ["and"] },
  { name: "Unlock Black Comet & Final Haunt (Team Combined)", types: ["and"] },
  { name: "Unlock Death Ruins & GUN Fortress (Team Combined)", types: ["and"] },
  { name: "Unlock Space Gadget & Lava Shelter (Team Combined)", types: ["and"] },
  { name: "Unlock Heal Cannon", types: ["finalhaunt", "unlock"] },
  { name: "Unlock Omochao Gun", types: ["cosmicfall", "unlock"] },
  { name: "Unlock Satellite Laser", types: ["gunfortress", "unlock"] },
  { name: "Unlock Egg Vaccuum", types: ["lavashelter", "unlock"] },
  { name: "Unlock Samurai Blade", types: ["blackcomet", "unlock"] },
  { name: "Unlock Any Level 2 Weapon", types: ["and"] },
  { name: "Ride 7 Unique Vehicles (Team Combined)", types: ["box"] },
  { name: "Finish GUN Fortress w/ 250+ Rings", types: ["gunfortress", "box"] },
  { name: "Hit 3 Life Capsules (GUN Fortress)", types: ["gunfortress", "box"] },
  { name: "Pacifist Black Comet Hero (3 enemies permitted)", types: ["blackcomet", "restricted"] },
  { name: "Finish Lava Shelter w/ 92 Shovel Ammo", types: ["lavashelter", "box"] },
  { name: "Hit 5 Life Capsules (Lava Shelter)", types: ["lavashelter", "box"] },
  { name: "Lava Shelter Dark without Guns", types: ["lavashelter", "restricted"] },
  { name: "Finish Cosmic Fall with 200+ Rings", types: ["cosmicfall", "box"] },
  { name: "Final Haunt Hero w/ 3 Activated Shields", types: ["finalhaunt", "restricted"] },
  { name: "Destroy 3 Ships in Final Haunt & finish", types: ["finalhaunt", "box"] },
  { name: "Destroy 6 Ships in Final Haunt & finish", types: ["finalhaunt", "box"] },
  { name: "The Doom 5 Keys OR Lost Impact Hero", types: ["or"] },
  { name: "Mad Matrix Dark OR Space Gadget Neutral", types: ["or"] },
  { name: "Lava Shelter 5 Keys OR Prison Island DNH", types: ["or"] },
  { name: "Unlock All Stage 2s OR Unlock 2 Stage 6s", types: ["or"] },
  { name: "Glyphic Canyon & Black Comet Hero", types: ["and"] },
  { name: "Digital Circuit, Death Ruins & GUN Fortress Hero", types: ["and"] },
  { name: "Iron Jungle & Lava Shelter Hero", types: ["and"] },
  { name: "Circus Park & Air Fleet Hero", types: ["and"] },
  { name: "The Doom & Lost Impact Hero", types: ["and"] },
  { name: "Cryptic Castle & Mad Matrix Hero", types: ["and"] },
  { name: "Iron Jungle & Lava Shelter Dark", types: ["and"] },
  { name: "Cryptic Castle & Circus Park Dark", types: ["and"] }
];

bingoList[3] = hardChallenges;


extraHardChallenges = [
  { name: "Defeat All 3 Egg Breakers (Team Combined)", types: [] },
  { name: "Defeat All 3 Final Bosses (Team Combined)", types: [] },
  { name: "Defeat Sonic & Diablon in 3 Different Stages (Team Combined)", types: [] },
  { name: "Defeat Egg Dealer in 3 Different Stages (Team Combined)", types: [] },
  { name: "Defeat Black Doom in 3 Different Stages (Team Combined)", types: [] },
  { name: "70 Keys (Team Combined)", types: [] },
  { name: "45 A Ranks (Team Combined)", types: [] },
  { name: "Unlock Every Stage (Team Combined)", types: [] }
];

bingoList[4] = extraHardChallenges;