bingoGenerator = require("./generators/generator_bases/isaac_generator.js");

var bingoList = [];

var easyChallenges = [
  { name: "Westopolis 5 Keys", types: ["westopolis"] },
  { name: "Digital Circuit 5 Keys", types: ["digitalcircuit"] },
  { name: "Glyphic Canyon 5 Keys", types: ["glyphiccanyon"] },
  { name: "Lethal Highway 5 Keys", types: ["lethalhighway"] },
  { name: "Cryptic Castle 5 Keys", types: ["crypticcastle"] },
  { name: "Prison Island 5 Keys", types: ["prisonisland"] },
  { name: "Circus Park 5 Keys", types: ["circuspark"] },
  { name: "Westopolis DNH", types: ["westopolis"] },
  { name: "Digital Circuit DH", types: ["digitalcircuit"] },
  { name: "Glyphic Canyon DNH", types: ["glyphiccanyon"] },
  { name: "Lethal Highway DH", types: ["lethalhighway"] },
  { name: "Cryptic Castle DNH", types: ["crypticcastle"] },
  { name: "Prison Island DNH", types: ["prisonisland"] },
  { name: "Circus Park DNH", types: ["circuspark"] },
  { name: "Westopolis 1 Shadow Box & finish", types: ["westopolis"] },
  { name: "Digital Circuit 2 Shadow Boxes & finish", types: ["digitalcircuit"] },
  { name: "Glyphic Canyon 4 Shadow Boxes & finish", types: ["glyphiccanyon"] },
  { name: "Lethal Highway 5 Shadow Boxes & finish", types: ["lethalhighway"] },
  { name: "Cryptic Castle 3 Shadow Boxes & finish", types: ["crypticcastle"] },
  { name: "Prison Island 3 Shadow Boxes & finish", types: ["prisonisland"] },
  { name: "Circus Park 2 Shadow Boxes & finish", types: ["circuspark"] },
  { name: "Westopolis Neutral w/o Chaos Control", types: ["westopolis"] },
  { name: "Westopolis Hero w/o Chaos Control", types: ["westopolis"] },
  { name: "Glyphic Canyon Dark w/o Chaos Control", types: ["glyphiccanyon"] },
  { name: "Glyphic Canyon Neutral w/o Chaos Control", types: ["glyphiccanyon"] },
  { name: "Glyphic Canyon Hero w/o Chaos Control", types: ["glyphiccanyon"] },
  { name: "Lethal Highway Dark w/o Chaos Control", types: ["lethalhighway"] },
  { name: "Prison Island Dark w/o Chaos Control", types: ["prisonisland"] },
  { name: "Prison Island Neutral w/o Chaos Control", types: ["prisonisland"] },
  { name: "Prison Island Hero w/o Chaos Control", types: ["prisonisland"] },
  { name: "Circus Park Dark w/o Chaos Control", types: ["circuspark"] },
  { name: "Circus Park Neutral w/o Chaos Control", types: ["circuspark"] },
  { name: "Circus Park Hero w/o Chaos Control", types: ["circuspark"] },
  { name: "Westopolis Dark via all 6 checkpoints", types: ["westopolis"] },
  { name: "Westopolis Neutral via all 6 checkpoints", types: ["westopolis"] },
  { name: "Westopolis Hero via all 6 checkpoints", types: ["westopolis"] },
  { name: "Digital Circuit Dark via all 7 checkpoints", types: ["digitalcircuit"] },
  { name: "Digital Circuit Hero via all 7 checkpoints", types: ["digitalcircuit"] },
  { name: "Glyphic Canyon Dark via all 8 checkpoints", types: ["glyphiccanyon"] },
  { name: "Glyphic Canyon Neutral via all 8 checkpoints", types: ["glyphiccanyon"] },
  { name: "Glyphic Canyon Hero via all 8 checkpoints", types: ["glyphiccanyon"] },
  { name: "Lethal Highway Dark via all 5 checkpoints", types: ["lethalhighway"] },
  { name: "Lethal Highway Hero via all 5 checkpoints", types: ["lethalhighway"] },
  { name: "Cryptic Castle Dark via all 8 checkpoints", types: ["crypticcastle"] },
  { name: "Cryptic Castle Neutral via all 8 checkpoints", types: ["crypticcastle"] },
  { name: "Cryptic Castle Hero via all 8 checkpoints", types: ["crypticcastle"] },
  { name: "Prison Island Dark via all 7 checkpoints", types: ["prisonisland"] },
  { name: "Prison Island Neutral via all 7 checkpoints", types: ["prisonisland"] },
  { name: "Prison Island Hero via all 7 checkpoints", types: ["prisonisland"] },
  { name: "Circus Park Dark via all 7 checkpoints", types: ["circuspark"] },
  { name: "Circus Park Neutral via all 7 checkpoints", types: ["circuspark"] },
  { name: "Circus Park Hero via all 7 checkpoints", types: ["circuspark"] },
  { name: "Defeat Black Bull w/o Chaos Control", types: ["blackbull"] },
  { name: "Defeat Black Bull without Guns", types: ["blackbull"] },
  { name: "Defeat Egg Breaker without Guns", types: ["eggbreaker"] },
  { name: "10 Keys", types: ["keys"] },
  { name: "25 Keys", types: ["keys"] },
  { name: "10 A Ranks", types: ["abc"] },
  { name: "25 A Ranks", types: ["abc"] },
  { name: "Die to a Gold Beetle", types: ["goldbeetle"] },
  { name: "Collect 88 Rings in 2P Game Level 3", types: ["2pgame"] },
  { name: "Collect 64 Rings in 2P Game Level 1", types: ["2pgame"] },
  { name: "Collect 50 Rings in 2P Game Level 2", types: ["2pgame"] },
  { name: "Ride the Armored Vehicle to the 5th Checkpoint (Westopolis)", types: ["westopolis"] },
  { name: "Finish Westopolis Hero or Dark with 100+ Road Signs", types: ["westopolis"] },
  { name: "Flip Over 2 Trucks (Westopolis)", types: ["westopolis"] },
  { name: "Defeat 44 Black Arms OR 34 GUN Soldiers then Westopolis Neutral", types: ["westopolis"] },
  { name: "Hit 4 Capsules (Westopolis)", types: ["westopolis"] },
  { name: "Hit 2 Life Capsules in Westopolis", types: ["westopolis"] },
  { name: "Hit a Life Capsule in Digital Circuit", types: ["digitalcircuit"] },
  { name: "Glyphic Canyon Hero with a higher Dark Score", types: ["glyphiccanyon"] },
  { name: "Glyphic Canyon Dark Pacifist", types: ["glyphiccanyon"] },
  { name: "Lethal Highway Dark Pacifist", types: ["lethalhighway"] },
  { name: "Lethal Highway Hero with NO Capsules", types: ["lethalhighway"] },
  { name: "Lethal Highway Dark with NO Capsules", types: ["lethalhighway"] },
  { name: "Save Cheese then Cream (Cryptic Castle)", types: ["crypticcastle"] },
  { name: "Prison Island Hero Pacifist", types: ["prisonisland"] },
  { name: "39 GUN Soldiers in Prison Island Hero", types: ["prisonisland"] },
  { name: "Hit a Flame Shield Capsule in Prison Island", types: ["prisonisland"] },
  { name: "Circus Park Neutral with 399 rings", types: ["circuspark"] },
  { name: "10 Keys OR 5 A Ranks", types: ["or"] },
  { name: "5 Keys in Westopolis OR 2 Keys in Stage 3", types: ["or"] },
  { name: "Have a 20+ Life Counter", types: ["box"] },
  { name: "Waste both meters in one stage (stand still, don't shoot)", types: ["restricted"] },
  { name: "Defeat a Black Oak w/ only an Egg Bazooka", types: ["restricted"] },
  { name: "Defeat a Big Foot w/ only homing attacks", types: ["restricted"] },
  { name: "Defeat a Sand Worm w/ only a Melee Weapon", types: ["restricted"] },
  { name: "Heal a Gold Beetle", types: ["goldbeetle"] },
  { name: "Defeat a Shadow Android w/ only spindashes", types: ["restricted"] },
  { name: "Defeat 10 enemies w/ a Chaos Control", types: ["restricted"] },
  { name: "360 No Scope a GUN Soldier", types: ["restricted"] }
];

bingoList[1] = easyChallenges;


var mediumChallenges = [
  { name: "Sky Troops 5 Keys", types: ["keys"] },
  { name: "Mad Matrix 5 Keys", types: ["keys"] },
  { name: "Death Ruins 5 Keys", types: ["keys"] },
  { name: "Iron Jungle 5 Keys", types: ["keys"] },
  { name: "Space Gadget 5 Keys", types: ["keys"] },
  { name: "Lost Impact 5 Keys", types: ["keys"] },
  { name: "Sky Troops DNH", types: ["dnh"] },
  { name: "Mad Matrix DNH", types: ["dnh"] },
  { name: "Death Ruins DH", types: ["dnh"] },
  { name: "Iron Jungle DNH", types: ["dnh"] },
  { name: "Space Gadget DNH", types: ["dnh"] },
  { name: "Lost Impact NH", types: ["dnh"] },
  { name: "Sky Troops 4 Shadow Boxes & finish", types: ["skytroops"] },
  { name: "Mad Matrix 3 Shadow Boxes & finish", types: ["madmatrix"] },
  { name: "Death Ruins 2 Shadow Boxes & finish", types: ["deathruins"] },
  { name: "Iron Jungle 3 Shadow Boxes & finish", types: ["ironjungle"] },
  { name: "Space Gadget 1 Shadow Box & finish", types: ["spacegadget"] },
  { name: "Lost Impact 1 Shadow Box & finish", types: ["lostimpact"] },
  { name: "Sky Troops Dark w/o Chaos Control", types: ["skytroops"] },
  { name: "Sky Troops Neutral w/o Chaos Control", types: ["skytroops"] },
  { name: "Sky Troops Hero w/o Chaos Control", types: ["skytroops"] },
  { name: "Mad Matrix Hero w/o Chaos Control", types: ["madmatrix"] },
  { name: "Death Ruins Dark w/o Chaos Control", types: ["deathruins"] },
  { name: "Iron Jungle Dark w/o Chaos Control", types: ["ironjungle"] },
  { name: "Iron Jungle Neutral w/o Chaos Control", types: ["ironjungle"] },
  { name: "Space Gadget Dark w/o Chaos Control", types: ["spacegadget"] },
  { name: "Space Gadget Neutral w/o Chaos Control", types: ["spacegadget"] },
  { name: "Space Gadget Hero w/o Chaos Control", types: ["spacegadget"] },
  { name: "Lost Impact Neutral w/o Chaos Control", types: ["lostimpact"] },
  { name: "Lost Impact Hero w/o Chaos Control", types: ["lostimpact"] },
  { name: "Sky Troops Dark via all 8 checkpoints", types: ["skytroops"] },
  { name: "Sky Troops Neutral via all 8 checkpoints", types: ["skytroops"] },
  { name: "Sky Troops Hero via all 8 checkpoints", types: ["skytroops"] },
  { name: "Mad Matrix Dark via all 6 checkpoints", types: ["madmatrix"] },
  { name: "Mad Matrix Neutral via all 6 checkpoints", types: ["madmatrix"] },
  { name: "Mad Matrix Hero via all 6 checkpoints", types: ["madmatrix"] },
  { name: "Death Ruins Dark via all 7 checkpoints", types: ["deathruins"] },
  { name: "Death Ruins Hero via all 7 checkpoints", types: ["deathruins"] },
  { name: "Iron Jungle Dark via all 8 checkpoints", types: ["ironjungle"] },
  { name: "Iron Jungle Neutral via all 8 checkpoints", types: ["ironjungle"] },
  { name: "Iron Jungle Hero via first 7 checkpoints", types: ["ironjungle"] },
  { name: "Space Gadget Dark via all 8 checkpoints", types: ["spacegadget"] },
  { name: "Space Gadget Neutral via all 8 checkpoints", types: ["spacegadget"] },
  { name: "Disable 5 Defense Shields in Space Gadget Hero", types: ["spacegadget"] },
  { name: "Lost Impact Neutral via all 8 checkpoints", types: ["lostimpact"] },
  { name: "Lost Impact Hero via all 8 checkpoints", types: ["lostimpact"] },
  { name: "Iron Jungle Hero Deathless", types: ["ironjungle"] },
  { name: "Defeat Both Black Bulls", types: ["and"] },
  { name: "3 Gold Beetles", types: ["goldbeetle"] },
  { name: "5 Gold Beetles", types: ["goldbeetle"] },
  { name: "Unlock Digital Circuit & Mad Matrix", types: ["and"] },
  { name: "Unlock Glyphic Canyon & Sky Troops", types: ["and"] },
  { name: "Unlock Prison Island & Iron Jungle", types: ["and"] },
  { name: "Unlock Cryptic Castle & Circus Park", types: ["and"] },
  { name: "Activate Yellow & Green Tower in Mad Matrix Neutral", types: ["madmatrix"] },
  { name: "Hit 4 Life Capsules (Death Ruins)", types: ["deathruins"] },
  { name: "Finish Iron Jungle w/ 100+ Tripod Ammo", types: ["ironjungle"] },
  { name: "Hit 1 Life Capsule (Space Gadget)", types: ["spacegadget"] },
  { name: "Finish Space Gadget w/ 200+ Rings", types: ["spacegadget"] },
  { name: "Finish Lost Impact w/ 300+ Rings", types: ["lostimpact"] },
  { name: "Hit 2 Life Capsules (Lost Impact)", types: ["lostimpact"] }
];

bingoList[2] = mediumChallenges;


var hardChallenges = [
  { name: "Lava Shelter 5 Keys", types: ["lavashelter"] },
  { name: "Cosmic Fall 5 Keys", types: ["cosmicfall"] },
  { name: "Final Haunt 5 Keys", types: ["finalhaunt"] },
  { name: "Lava Shelter DH", types: ["lavashelter"] },
  { name: "Cosmic Fall DH", types: ["cosmicfall"] },
  { name: "Final Haunt DH", types: ["finalhaunt"] },
  { name: "Lava Shelter 3 Shadow Boxes & finish", types: ["lavashelter"] },
  { name: "Cosmic Fall 2 Shadow Boxes & finish", types: ["cosmicfall"] },
  { name: "Final Haunt 3 Shadow Boxes & finish", types: ["finalhaunt"] },
  { name: "Lava Shelter Dark w/o Chaos Control", types: ["lavashelter"] },
  { name: "Lava Shelter Hero w/o Chaos Control", types: ["lavashelter"] },
  { name: "Cosmic Fall Dark w/o Chaos Control", types: ["cosmicfall"] },
  { name: "Cosmic Fall Hero w/o Chaos Control", types: ["cosmicfall"] },
  { name: "Final Haunt Dark w/o Chaos Control", types: ["finalhaunt"] },
  { name: "Final Haunt Hero w/o Chaos Control", types: ["finalhaunt"] },
  { name: "Lava Shelter Dark via all 8 checkpoints", types: ["lavashelter"] },
  { name: "Lava Shelter Hero via all 8 checkpoints", types: ["lavashelter"] },
  { name: "Cosmic Fall Dark via all 7 checkpoints", types: ["cosmicfall"] },
  { name: "Cosmic Fall Hero via all 7 checkpoints", types: ["cosmicfall"] },
  { name: "Final Haunt Dark via all 8 checkpoints", types: ["finalhaunt"] },
  { name: "Final Haunt Hero via all 8 checkpoints", types: ["finalhaunt"] },
  { name: "Defeat Sonic & Diablon without Guns", types: ["sonic&diablon"] },
  { name: "Defeat Egg Dealer without Guns", types: ["eggdealer"] },
  { name: "Defeat Black Doom without Guns", types: ["blackdoom"] },
  { name: "Unlock Heal Cannon", types: ["finalhaunt"] },
  { name: "Unlock Omochao Gun", types: ["cosmicfall"] },
  { name: "Unlock Egg Vaccuum", types: ["lavashelter"] },
  { name: "Finish Lava Shelter w/ 92 Shovel Ammo", types: ["lavashelter"] },
  { name: "Hit 5 Life Capsules (Lava Shelter)", types: ["lavashelter"] },
  { name: "Lava Shelter Dark without Guns", types: ["lavashelter"] },
  { name: "Finish Cosmic Fall with 200+ Rings", types: ["cosmicfall"] },
  { name: "Final Haunt Hero w/ 3 Activated Shields", types: ["finalhaunt"] },
  { name: "Destroy 3 Ships in Final Haunt & finish", types: ["finalhaunt"] },
  { name: "Destroy 6 Ships in Final Haunt & finish", types: ["finalhaunt"] },
  { name: "Mad Matrix Dark OR Space Gadget Neutral", types: ["or"] },
  { name: "Lava Shelter 5 Keys OR Prison Island DNH", types: ["or"] },
  { name: "Glyphic Canyon & Black Comet Hero", types: ["and"] },
  { name: "Digital Circuit, Death Ruins & GUN Fortress Hero", types: ["and"] },
  { name: "Iron Jungle & Lava Shelter Hero", types: ["and"] },
  { name: "Cryptic Castle & Mad Matrix Hero", types: ["and"] },
  { name: "Iron Jungle & Lava Shelter Dark", types: ["and"] },
  { name: "Cryptic Castle & Circus Park Dark", types: ["and"] }
];

bingoList[3] = hardChallenges;


extraHardChallenges = [
  { name: "1 Level 2 Weapon OR 3 Level 1 Weapons", types: [] },
  { name: "Unlock Any Level 2 Weapon", types: [] },
  { name: "Unlock 3 Level 1 Weapons", types: [] }
];

bingoList[4] = extraHardChallenges;