bingoGenerator = require("./generators/generator_bases/isaac_generator.js");

var bingoList = [];

var easyChallenges = [
  { name: "Westopolis 5 Keys", types: ["westopolis"] },
  { name: "Digital Circuit 5 Keys", types: ["digitalcircuit"] },
  { name: "Glyphic Canyon 5 Keys", types: ["glyphiccanyon"] },
  { name: "Lethal Highway 5 Keys", types: ["lethalhighway"] },
  { name: "Cryptic Castle 5 Keys", types: ["crypticcastle"] },
  { name: "Prison Island 5 Keys", types: ["prisonisland"] },
  { name: "Circus Park 5 Keys", types: ["circuspark"] },
  { name: "Westopolis DNH", types: ["westopolis"] },
  { name: "Digital Circuit DH", types: ["digitalcircuit"] },
  { name: "Glyphic Canyon DNH", types: ["glyphiccanyon"] },
  { name: "Lethal Highway DH", types: ["lethalhighway"] },
  { name: "Cryptic Castle DNH", types: ["crypticcastle"] },
  { name: "Prison Island DNH", types: ["prisonisland"] },
  { name: "Circus Park DNH", types: ["circuspark"] },
  { name: "Westopolis 1 Shadow Box & finish", types: ["westopolis"] },
  { name: "Digital Circuit 2 Shadow Boxes & finish", types: ["digitalcircuit"] },
  { name: "Glyphic Canyon 4 Shadow Boxes & finish", types: ["glyphiccanyon"] },
  { name: "Lethal Highway 5 Shadow Boxes & finish", types: ["lethalhighway"] },
  { name: "Cryptic Castle 3 Shadow Boxes & finish", types: ["crypticcastle"] },
  { name: "Prison Island 3 Shadow Boxes & finish", types: ["prisonisland"] },
  { name: "Circus Park 2 Shadow Boxes & finish", types: ["circuspark"] },
  { name: "Westopolis Neutral w/o Chaos Control", types: ["westopolis"] },
  { name: "Westopolis Hero w/o Chaos Control", types: ["westopolis"] },
  { name: "Glyphic Canyon Dark w/o Chaos Control", types: ["glyphiccanyon"] },
  { name: "Glyphic Canyon Neutral w/o Chaos Control", types: ["glyphiccanyon"] },
  { name: "Glyphic Canyon Hero w/o Chaos Control", types: ["glyphiccanyon"] },
  { name: "Lethal Highway Dark w/o Chaos Control", types: ["lethalhighway"] },
  { name: "Prison Island Dark w/o Chaos Control", types: ["prisonisland"] },
  { name: "Prison Island Neutral w/o Chaos Control", types: ["prisonisland"] },
  { name: "Prison Island Hero w/o Chaos Control", types: ["prisonisland"] },
  { name: "Circus Park Dark w/o Chaos Control", types: ["circuspark"] },
  { name: "Circus Park Neutral w/o Chaos Control", types: ["circuspark"] },
  { name: "Circus Park Hero w/o Chaos Control", types: ["circuspark"] },
  { name: "Westopolis Dark via all 6 checkpoints", types: ["westopolis"] },
  { name: "Westopolis Neutral via all 6 checkpoints", types: ["westopolis"] },
  { name: "Westopolis Hero via all 6 checkpoints", types: ["westopolis"] },
  { name: "Digital Circuit Dark via all 7 checkpoints", types: ["digitalcircuit"] },
  { name: "Digital Circuit Hero via all 7 checkpoints", types: ["digitalcircuit"] },
  { name: "Glyphic Canyon Dark via all 8 checkpoints", types: ["glyphiccanyon"] },
  { name: "Glyphic Canyon Neutral via all 8 checkpoints", types: ["glyphiccanyon"] },
  { name: "Glyphic Canyon Hero via all 8 checkpoints", types: ["glyphiccanyon"] },
  { name: "Lethal Highway Dark via all 5 checkpoints", types: ["lethalhighway"] },
  { name: "Lethal Highway Hero via all 5 checkpoints", types: ["lethalhighway"] },
  { name: "Cryptic Castle Dark via all 8 checkpoints", types: ["crypticcastle"] },
  { name: "Cryptic Castle Neutral via all 8 checkpoints", types: ["crypticcastle"] },
  { name: "Cryptic Castle Hero via all 8 checkpoints", types: ["crypticcastle"] },
  { name: "Prison Island Dark via all 7 checkpoints", types: ["prisonisland"] },
  { name: "Prison Island Neutral via all 7 checkpoints", types: ["prisonisland"] },
  { name: "Prison Island Hero via all 7 checkpoints", types: ["prisonisland"] },
  { name: "Circus Park Dark via all 7 checkpoints", types: ["circuspark"] },
  { name: "Circus Park Neutral via all 7 checkpoints", types: ["circuspark"] },
  { name: "Circus Park Hero via all 7 checkpoints", types: ["circuspark"] },
  { name: "Defeat Black Bull w/o Chaos Control", types: ["blackbull"] },
  { name: "Defeat Black Bull without Guns", types: ["blackbull"] },
  { name: "Defeat Egg Breaker without Guns", types: ["eggbreaker"] },
  { name: "10 Keys", types: ["keys"] },
  { name: "25 Keys", types: ["keys"] },
  { name: "10 A Ranks", types: ["abc"] },
  { name: "25 A Ranks", types: ["abc"] },
  { name: "Die to a Gold Beetle", types: ["goldbeetle"] },
  { name: "Collect 88 Rings in 2P Game Level 3", types: ["2pgame"] },
  { name: "Collect 64 Rings in 2P Game Level 1", types: ["2pgame"] },
  { name: "Collect 50 Rings in 2P Game Level 2", types: ["2pgame"] },
  { name: "Ride the Armored Vehicle to the 5th Checkpoint (Westopolis)", types: ["westopolis"] },
  { name: "Finish Westopolis Hero or Dark with 100+ Road Signs", types: ["westopolis"] },
  { name: "Flip Over 2 Trucks (Westopolis)", types: ["westopolis"] },
  { name: "Defeat 44 Black Arms OR 34 GUN Soldiers then Westopolis Neutral", types: ["westopolis"] },
  { name: "Hit 4 Capsules (Westopolis)", types: ["westopolis"] },
  { name: "Hit 2 Life Capsules in Westopolis", types: ["westopolis"] },
  { name: "Hit a Life Capsule in Digital Circuit", types: ["digitalcircuit"] },
  { name: "Glyphic Canyon Hero with a higher Dark Score", types: ["glyphiccanyon"] },
  { name: "Glyphic Canyon Dark Pacifist", types: ["glyphiccanyon"] },
  { name: "Lethal Highway Dark Pacifist", types: ["lethalhighway"] },
  { name: "Lethal Highway Hero with NO Capsules", types: ["lethalhighway"] },
  { name: "Lethal Highway Dark with NO Capsules", types: ["lethalhighway"] },
  { name: "Save Cheese then Cream (Cryptic Castle)", types: ["crypticcastle"] },
  { name: "Prison Island Hero Pacifist", types: ["prisonisland"] },
  { name: "39 GUN Soldiers in Prison Island Hero", types: ["prisonisland"] },
  { name: "Hit a Flame Shield Capsule in Prison Island", types: ["prisonisland"] },
  { name: "Circus Park Neutral with 399 rings", types: ["circuspark"] },
  { name: "10 Keys OR 5 A Ranks", types: ["or"] },
  { name: "5 Keys in Westopolis OR 2 Keys in Stage 3", types: ["or"] },
  { name: "Finish a stage with 500+ ammo", types: ["box"] },
  { name: "Finish a stage with 100+ special weapon ammo", types: ["box"] },
  { name: "Finish a stage with 50+ special weapon ammo", types: ["box"] },
  { name: "Have a 20+ Life Counter", types: ["box"] },
  { name: "Waste both meters in one stage (stand still, don't shoot)", types: ["restricted"] },
  { name: "Defeat a Black Oak w/ only an Egg Bazooka", types: ["restricted"] },
  { name: "Defeat a Big Foot w/ only homing attacks", types: ["restricted"] },
  { name: "Defeat a Sand Worm w/ only a Melee Weapon", types: ["restricted"] },
  { name: "Heal a Gold Beetle", types: ["goldbeetle"] },
  { name: "Defeat a Shadow Android w/ only spindashes", types: ["restricted"] },
  { name: "Defeat 10 enemies w/ a Chaos Control", types: ["restricted"] },
  { name: "360 No Scope a GUN Soldier", types: ["restricted"] }
];

bingoList[1] = easyChallenges;


var mediumChallenges = [
  { name: "Central City 5 Keys", types: ["keys"] },
  { name: "The Doom 5 Keys", types: ["keys"] },
  { name: "Sky Troops 5 Keys", types: ["keys"] },
  { name: "The ARK 5 Keys", types: ["keys"] },
  { name: "Air Fleet 5 Keys", types: ["keys"] },
  { name: "Iron Jungle 5 Keys", types: ["keys"] },
  { name: "Central City DH", types: ["dnh"] },
  { name: "The Doom DNH", types: ["dnh"] },
  { name: "Sky Troops DNH", types: ["dnh"] },
  { name: "The ARK DN", types: ["dnh"] },
  { name: "Air Fleet DNH", types: ["dnh"] },
  { name: "Iron Jungle DNH", types: ["dnh"] },
  { name: "Central City 2 Shadow Boxes & finish", types: ["centralcity"] },
  { name: "The Doom 3 Shadow Boxes & finish", types: ["thedoom"] },
  { name: "Sky Troops 4 Shadow Boxes & finish", types: ["skytroops"] },
  { name: "The ARK 2 Shadow Boxes & finish", types: ["theark"] },
  { name: "Air Fleet 6 Shadow Boxes & finish", types: ["airfleet"] },
  { name: "Iron Jungle 3 Shadow Boxes & finish", types: ["ironjungle"] },
  { name: "The Doom Neutral w/o Chaos Control", types: ["thedoom"] },
  { name: "The Doom Hero w/o Chaos Control", types: ["thedoom"] },
  { name: "Sky Troops Dark w/o Chaos Control", types: ["skytroops"] },
  { name: "Sky Troops Neutral w/o Chaos Control", types: ["skytroops"] },
  { name: "Sky Troops Hero w/o Chaos Control", types: ["skytroops"] },
  { name: "Air Fleet Neutral w/o Chaos Control", types: ["airfleet"] },
  { name: "Air Fleet Hero w/o Chaos Control", types: ["airfleet"] },
  { name: "Iron Jungle Dark w/o Chaos Control", types: ["ironjungle"] },
  { name: "Iron Jungle Neutral w/o Chaos Control", types: ["ironjungle"] },
  { name: "Central City Dark via all 6 checkpoints", types: ["centralcity"] },
  { name: "Central City Hero via all 6 checkpoints", types: ["centralcity"] },
  { name: "The Doom Dark via all 6 checkpoints", types: ["thedoom"] },
  { name: "The Doom Neutral via all 6 checkpoints", types: ["thedoom"] },
  { name: "The Doom Hero via all 6 checkpoints", types: ["thedoom"] },
  { name: "Sky Troops Dark via all 8 checkpoints", types: ["skytroops"] },
  { name: "Sky Troops Neutral via all 8 checkpoints", types: ["skytroops"] },
  { name: "Sky Troops Hero via all 8 checkpoints", types: ["skytroops"] },
  { name: "The ARK Dark via all 8 checkpoints", types: ["theark"] },
  { name: "The ARK Neutral via all 8 checkpoints", types: ["theark"] },
  { name: "Air Fleet Dark via first 7 checkpoints", types: ["airfleet"] },
  { name: "Air Fleet Neutral via all 8 checkpoints", types: ["airfleet"] },
  { name: "Air Fleet Hero via all 8 checkpoints", types: ["airfleet"] },
  { name: "Iron Jungle Dark via all 8 checkpoints", types: ["ironjungle"] },
  { name: "Iron Jungle Neutral via all 8 checkpoints", types: ["ironjungle"] },
  { name: "Iron Jungle Hero via first 7 checkpoints", types: ["ironjungle"] },
  { name: "Air Fleet Dark Deathless", types: ["airfleet"] },
  { name: "Iron Jungle Hero Deathless", types: ["ironjungle"] },
  { name: "Defeat Both Heavy Dog & Blue Falcon", types: ["and"] },
  { name: "3 Gold Beetles", types: ["goldbeetle"] },
  { name: "5 Gold Beetles", types: ["goldbeetle"] },
  { name: "Defeat Heavy Dog without Guns", types: ["heavydog"] },
  { name: "Defeat Blue Falcon without Guns", types: ["bluefalcon"] },
  { name: "Unlock Westopolis & Central City", types: ["and"] },
  { name: "Unlock Digital Circuit & Mad Matrix", types: ["and"] },
  { name: "Unlock Glyphic Canyon & Sky Troops", types: ["and"] },
  { name: "Unlock Prison Island & Iron Jungle", types: ["and"] },
  { name: "Unlock Lethal Highway & Air Fleet", types: ["and"] },
  { name: "Unlock Cryptic Castle & Circus Park", types: ["and"] },
  { name: "Central City Dark with 19 small bombs removed", types: ["centralcity"] },
  { name: "Find a Chaos Control Orb in Central City", types: ["centralcity"] },
  { name: "Hit 11 Capsules (The Doom)", types: ["thedoom"] },
  { name: "Hit 3 Life Capsules (The Doom)", types: ["thedoom"] },
  { name: "Use 6 Dash Rings (The Doom)", types: ["thedoom"] },
  { name: "Finish The ARK w/ 100+ Rings", types: ["theark"] },
  { name: "Fail Air Fleet Dark then do Hero", types: ["airfleet"] },
  { name: "Defeat 34 Black Arms in Air Fleet Dark", types: ["airfleet"] },
  { name: "Finish Iron Jungle w/ 100+ Tripod Ammo", types: ["ironjungle"] }
];

bingoList[2] = mediumChallenges;


var hardChallenges = [
  { name: "GUN Fortress 5 Keys", types: ["gunfortress"] },
  { name: "Black Comet 5 Keys", types: ["blackcomet"] },
  { name: "Lava Shelter 5 Keys", types: ["lavashelter"] },
  { name: "GUN Fortress DH", types: ["gunfortress"] },
  { name: "Black Comet DH", types: ["blackcomet"] },
  { name: "Lava Shelter DH", types: ["lavashelter"] },
  { name: "GUN Fortress 2 Shadow Boxes & finish", types: ["gunfortress"] },
  { name: "Black Comet 5 Shadow Boxes & finish", types: ["blackcomet"] },
  { name: "Lava Shelter 3 Shadow Boxes & finish", types: ["lavashelter"] },
  { name: "GUN Fortress Hero w/o Chaos Control", types: ["gunfortress"] },
  { name: "Black Comet Hero w/o Chaos Control", types: ["blackcomet"] },
  { name: "Lava Shelter Dark w/o Chaos Control", types: ["lavashelter"] },
  { name: "Lava Shelter Hero w/o Chaos Control", types: ["lavashelter"] },
  { name: "GUN Fortress Dark via all 7 checkpoints", types: ["gunfortress"] },
  { name: "GUN Fortress Hero via all 7 checkpoints", types: ["gunfortress"] },
  { name: "Black Comet Dark via all 8 checkpoints", types: ["blackcomet"] },
  { name: "Black Comet Hero via all 8 checkpoints", types: ["blackcomet"] },
  { name: "Lava Shelter Dark via all 8 checkpoints", types: ["lavashelter"] },
  { name: "Lava Shelter Hero via all 8 checkpoints", types: ["lavashelter"] },
  { name: "Defeat Sonic & Diablon without Guns", types: ["sonic&diablon"] },
  { name: "Defeat Egg Dealer without Guns", types: ["eggdealer"] },
  { name: "Defeat Black Doom without Guns", types: ["blackdoom"] },
  { name: "Unlock Satellite Laser", types: ["gunfortress"] },
  { name: "Unlock Egg Vaccuum", types: ["lavashelter"] },
  { name: "Unlock Samurai Blade", types: ["blackcomet"] },
  { name: "Finish GUN Fortress w/ 250+ Rings", types: ["gunfortress"] },
  { name: "Hit 3 Life Capsules (GUN Fortress)", types: ["gunfortress"] },
  { name: "Pacifist Black Comet Hero (3 enemies permitted)", types: ["blackcomet"] },
  { name: "Finish Lava Shelter w/ 92 Shovel Ammo", types: ["lavashelter"] },
  { name: "Hit 5 Life Capsules (Lava Shelter)", types: ["lavashelter"] },
  { name: "Lava Shelter Dark without Guns", types: ["lavashelter"] },
  { name: "Lava Shelter 5 Keys OR Prison Island DNH", types: ["or"] },
  { name: "Glyphic Canyon & Black Comet Hero", types: ["and"] },
  { name: "Iron Jungle & Lava Shelter Hero", types: ["and"] },
  { name: "Circus Park & Air Fleet Hero", types: ["and"] },
  { name: "Iron Jungle & Lava Shelter Dark", types: ["and"] },
  { name: "Cryptic Castle & Circus Park Dark", types: ["and"] }
];

bingoList[3] = hardChallenges;


extraHardChallenges = [
  { name: "1 Level 2 Weapon OR 3 Level 1 Weapons", types: [] },
  { name: "Unlock Any Level 2 Weapon", types: [] },
  { name: "Unlock 3 Level 1 Weapons", types: [] }
];

bingoList[4] = extraHardChallenges;