bingoGenerator = require("./generators/generator_bases/isaac_generator.js");

var bingoList = [];

var easyChallenges = [
{ name: "Radical City in Balloon Mode with Amy", types: ["RadicalCityBalloonModeAmy"]},
{ name: "Radical City in Balloon Mode with Knuckles", types: ["RadicalCityBalloonModeKnuckles"]},
{ name: "Radical City in Balloon Mode with Sonic", types: ["RadicalCityBalloonModeSonic"]},
{ name: "Radical City in Balloon Mode with Tails", types: ["RadicalCityBalloonModeTails"]},
{ name: "Radical City in Grand Prix with Amy", types: ["RadicalCityGrandPrixAmy"]},
{ name: "Radical City in Grand Prix with Knuckles", types: ["RadicalCityGrandPrixKnuckles"]},
{ name: "Radical City in Grand Prix with Sonic", types: ["RadicalCityGrandPrixSonic"]},
{ name: "Radical City in Grand Prix with Tails", types: ["RadicalCityGrandPrixTails"]},
{ name: "Radical City in Tag Mode with Amy", types: ["RadicalCityTagModeAmy"]},
{ name: "Radical City in Tag Mode with Knuckles", types: ["RadicalCityTagModeKnuckles"]},
{ name: "Radical City in Tag Mode with Sonic", types: ["RadicalCityTagModeSonic"]},
{ name: "Radical City in Tag Mode with Tails", types: ["RadicalCityTagModeTails"]},
{ name: "Radical City in Time Trial (Normal) with Amy", types: ["RadicalCityTimeTrialNormalAmy"]},
{ name: "Radical City in Time Trial (Normal) with Knuckles", types: ["RadicalCityTimeTrialNormalKnuckles"]},
{ name: "Radical City in Time Trial (Normal) with Sonic", types: ["RadicalCityTimeTrialNormalSonic"]},
{ name: "Radical City in Time Trial (Normal) with Tails", types: ["RadicalCityTimeTrialNormalTails"]},
{ name: "Radical City in Time Trial (Reverse) with Amy", types: ["RadicalCityTimeTrialReverseAmy"]},
{ name: "Radical City in Time Trial (Reverse) with Knuckles", types: ["RadicalCityTimeTrialReverseKnuckles"]},
{ name: "Radical City in Time Trial (Reverse) with Sonic", types: ["RadicalCityTimeTrialReverseSonic"]},
{ name: "Radical City in Time Trial (Reverse) with Tails", types: ["RadicalCityTimeTrialReverseTails"]},
{ name: "Reactive Factory in Balloon Mode with Amy", types: ["ReactiveFactoryBalloonModeAmy"]},
{ name: "Reactive Factory in Balloon Mode with Knuckles", types: ["ReactiveFactoryBalloonModeKnuckles"]},
{ name: "Reactive Factory in Balloon Mode with Sonic", types: ["ReactiveFactoryBalloonModeSonic"]},
{ name: "Reactive Factory in Balloon Mode with Tails", types: ["ReactiveFactoryBalloonModeTails"]},
{ name: "Reactive Factory in Grand Prix with Amy", types: ["ReactiveFactoryGrandPrixAmy"]},
{ name: "Reactive Factory in Grand Prix with Knuckles", types: ["ReactiveFactoryGrandPrixKnuckles"]},
{ name: "Reactive Factory in Grand Prix with Sonic", types: ["ReactiveFactoryGrandPrixSonic"]},
{ name: "Reactive Factory in Grand Prix with Tails", types: ["ReactiveFactoryGrandPrixTails"]},
{ name: "Reactive Factory in Tag Mode with Amy", types: ["ReactiveFactoryTagModeAmy"]},
{ name: "Reactive Factory in Tag Mode with Knuckles", types: ["ReactiveFactoryTagModeKnuckles"]},
{ name: "Reactive Factory in Tag Mode with Sonic", types: ["ReactiveFactoryTagModeSonic"]},
{ name: "Reactive Factory in Tag Mode with Tails", types: ["ReactiveFactoryTagModeTails"]},
{ name: "Reactive Factory in Time Trial (Normal) with Amy", types: ["ReactiveFactoryTimeTrialNormalAmy"]},
{ name: "Reactive Factory in Time Trial (Normal) with Knuckles", types: ["ReactiveFactoryTimeTrialNormalKnuckles"]},
{ name: "Reactive Factory in Time Trial (Normal) with Sonic", types: ["ReactiveFactoryTimeTrialNormalSonic"]},
{ name: "Reactive Factory in Time Trial (Normal) with Tails", types: ["ReactiveFactoryTimeTrialNormalTails"]},
{ name: "Reactive Factory in Time Trial (Reverse) with Amy", types: ["ReactiveFactoryTimeTrialReverseAmy"]},
{ name: "Reactive Factory in Time Trial (Reverse) with Knuckles", types: ["ReactiveFactoryTimeTrialReverseKnuckles"]},
{ name: "Reactive Factory in Time Trial (Reverse) with Sonic", types: ["ReactiveFactoryTimeTrialReverseSonic"]},
{ name: "Reactive Factory in Time Trial (Reverse) with Tails", types: ["ReactiveFactoryTimeTrialReverseTails"]},
{ name: "Regal Ruin in Balloon Mode with Amy", types: ["RegalRuinBalloonModeAmy"]},
{ name: "Regal Ruin in Balloon Mode with Knuckles", types: ["RegalRuinBalloonModeKnuckles"]},
{ name: "Regal Ruin in Balloon Mode with Sonic", types: ["RegalRuinBalloonModeSonic"]},
{ name: "Regal Ruin in Balloon Mode with Tails", types: ["RegalRuinBalloonModeTails"]},
{ name: "Regal Ruin in Grand Prix with Amy", types: ["RegalRuinGrandPrixAmy"]},
{ name: "Regal Ruin in Grand Prix with Knuckles", types: ["RegalRuinGrandPrixKnuckles"]},
{ name: "Regal Ruin in Grand Prix with Sonic", types: ["RegalRuinGrandPrixSonic"]},
{ name: "Regal Ruin in Grand Prix with Tails", types: ["RegalRuinGrandPrixTails"]},
{ name: "Regal Ruin in Tag Mode with Amy", types: ["RegalRuinTagModeAmy"]},
{ name: "Regal Ruin in Tag Mode with Knuckles", types: ["RegalRuinTagModeKnuckles"]},
{ name: "Regal Ruin in Tag Mode with Sonic", types: ["RegalRuinTagModeSonic"]},
{ name: "Regal Ruin in Tag Mode with Tails", types: ["RegalRuinTagModeTails"]},
{ name: "Regal Ruin in Time Trial (Normal) with Amy", types: ["RegalRuinTimeTrialNormalAmy"]},
{ name: "Regal Ruin in Time Trial (Normal) with Knuckles", types: ["RegalRuinTimeTrialNormalKnuckles"]},
{ name: "Regal Ruin in Time Trial (Normal) with Sonic", types: ["RegalRuinTimeTrialNormalSonic"]},
{ name: "Regal Ruin in Time Trial (Normal) with Tails", types: ["RegalRuinTimeTrialNormalTails"]},
{ name: "Regal Ruin in Time Trial (Reverse) with Amy", types: ["RegalRuinTimeTrialReverseAmy"]},
{ name: "Regal Ruin in Time Trial (Reverse) with Knuckles", types: ["RegalRuinTimeTrialReverseKnuckles"]},
{ name: "Regal Ruin in Time Trial (Reverse) with Sonic", types: ["RegalRuinTimeTrialReverseSonic"]},
{ name: "Regal Ruin in Time Trial (Reverse) with Tails", types: ["RegalRuinTimeTrialReverseTails"]},
{ name: "Resort Island in Balloon Mode with Amy", types: ["ResortIslandBalloonModeAmy"]},
{ name: "Resort Island in Balloon Mode with Knuckles", types: ["ResortIslandBalloonModeKnuckles"]},
{ name: "Resort Island in Balloon Mode with Sonic", types: ["ResortIslandBalloonModeSonic"]},
{ name: "Resort Island in Balloon Mode with Tails", types: ["ResortIslandBalloonModeTails"]},
{ name: "Resort Island in Grand Prix with Amy", types: ["ResortIslandGrandPrixAmy"]},
{ name: "Resort Island in Grand Prix with Knuckles", types: ["ResortIslandGrandPrixKnuckles"]},
{ name: "Resort Island in Grand Prix with Sonic", types: ["ResortIslandGrandPrixSonic"]},
{ name: "Resort Island in Grand Prix with Tails", types: ["ResortIslandGrandPrixTails"]},
{ name: "Resort Island in Tag Mode with Amy", types: ["ResortIslandTagModeAmy"]},
{ name: "Resort Island in Tag Mode with Knuckles", types: ["ResortIslandTagModeKnuckles"]},
{ name: "Resort Island in Tag Mode with Sonic", types: ["ResortIslandTagModeSonic"]},
{ name: "Resort Island in Tag Mode with Tails", types: ["ResortIslandTagModeTails"]},
{ name: "Resort Island in Time Trial (Normal) with Amy", types: ["ResortIslandTimeTrialNormalAmy"]},
{ name: "Resort Island in Time Trial (Normal) with Knuckles", types: ["ResortIslandTimeTrialNormalKnuckles"]},
{ name: "Resort Island in Time Trial (Normal) with Sonic", types: ["ResortIslandTimeTrialNormalSonic"]},
{ name: "Resort Island in Time Trial (Normal) with Tails", types: ["ResortIslandTimeTrialNormalTails"]},
{ name: "Resort Island in Time Trial (Reverse) with Amy", types: ["ResortIslandTimeTrialReverseAmy"]},
{ name: "Resort Island in Time Trial (Reverse) with Knuckles", types: ["ResortIslandTimeTrialReverseKnuckles"]},
{ name: "Resort Island in Time Trial (Reverse) with Sonic", types: ["ResortIslandTimeTrialReverseSonic"]},
{ name: "Resort Island in Time Trial (Reverse) with Tails", types: ["ResortIslandTimeTrialReverseTails"]}
];

bingoList[1] = easyChallenges;


var mediumChallenges = [
{ name: "Radical City in Balloon Mode with Egg Robo", types: ["RadicalCityBalloonModeEggRobo"]},
{ name: "Radical City in Balloon Mode with Metal Knuckles", types: ["RadicalCityBalloonModeMetalKnuckles"]},
{ name: "Radical City in Balloon Mode with Metal Sonic", types: ["RadicalCityBalloonModeMetalSonic"]},
{ name: "Radical City in Balloon Mode with Tails Doll", types: ["RadicalCityBalloonModeTailsDoll"]},
{ name: "Radical City in Grand Prix with Egg Robo", types: ["RadicalCityGrandPrixEggRobo"]},
{ name: "Radical City in Grand Prix with Metal Knuckles", types: ["RadicalCityGrandPrixMetalKnuckles"]},
{ name: "Radical City in Grand Prix with Metal Sonic", types: ["RadicalCityGrandPrixMetalSonic"]},
{ name: "Radical City in Grand Prix with Tails Doll", types: ["RadicalCityGrandPrixTailsDoll"]},
{ name: "Radical City in Tag Mode with Egg Robo", types: ["RadicalCityTagModeEggRobo"]},
{ name: "Radical City in Tag Mode with Metal Knuckles", types: ["RadicalCityTagModeMetalKnuckles"]},
{ name: "Radical City in Tag Mode with Metal Sonic", types: ["RadicalCityTagModeMetalSonic"]},
{ name: "Radical City in Tag Mode with Tails Doll", types: ["RadicalCityTagModeTailsDoll"]},
{ name: "Radical City in Time Trial (Normal) with Egg Robo", types: ["RadicalCityTimeTrialNormalEggRobo"]},
{ name: "Radical City in Time Trial (Normal) with Metal Knuckles", types: ["RadicalCityTimeTrialNormalMetalKnuckles"]},
{ name: "Radical City in Time Trial (Normal) with Metal Sonic", types: ["RadicalCityTimeTrialNormalMetalSonic"]},
{ name: "Radical City in Time Trial (Normal) with Tails Doll", types: ["RadicalCityTimeTrialNormalTailsDoll"]},
{ name: "Radical City in Time Trial (Reverse) with Egg Robo", types: ["RadicalCityTimeTrialReverseEggRobo"]},
{ name: "Radical City in Time Trial (Reverse) with Metal Knuckles", types: ["RadicalCityTimeTrialReverseMetalKnuckles"]},
{ name: "Radical City in Time Trial (Reverse) with Metal Sonic", types: ["RadicalCityTimeTrialReverseMetalSonic"]},
{ name: "Radical City in Time Trial (Reverse) with Tails Doll", types: ["RadicalCityTimeTrialReverseTailsDoll"]},
{ name: "Reactive Factory in Balloon Mode with Egg Robo", types: ["ReactiveFactoryBalloonModeEggRobo"]},
{ name: "Reactive Factory in Balloon Mode with Metal Knuckles", types: ["ReactiveFactoryBalloonModeMetalKnuckles"]},
{ name: "Reactive Factory in Balloon Mode with Metal Sonic", types: ["ReactiveFactoryBalloonModeMetalSonic"]},
{ name: "Reactive Factory in Balloon Mode with Tails Doll", types: ["ReactiveFactoryBalloonModeTailsDoll"]},
{ name: "Reactive Factory in Grand Prix with Egg Robo", types: ["ReactiveFactoryGrandPrixEggRobo"]},
{ name: "Reactive Factory in Grand Prix with Metal Knuckles", types: ["ReactiveFactoryGrandPrixMetalKnuckles"]},
{ name: "Reactive Factory in Grand Prix with Metal Sonic", types: ["ReactiveFactoryGrandPrixMetalSonic"]},
{ name: "Reactive Factory in Grand Prix with Tails Doll", types: ["ReactiveFactoryGrandPrixTailsDoll"]},
{ name: "Reactive Factory in Tag Mode with Egg Robo", types: ["ReactiveFactoryTagModeEggRobo"]},
{ name: "Reactive Factory in Tag Mode with Metal Knuckles", types: ["ReactiveFactoryTagModeMetalKnuckles"]},
{ name: "Reactive Factory in Tag Mode with Metal Sonic", types: ["ReactiveFactoryTagModeMetalSonic"]},
{ name: "Reactive Factory in Tag Mode with Tails Doll", types: ["ReactiveFactoryTagModeTailsDoll"]},
{ name: "Reactive Factory in Time Trial (Normal) with Egg Robo", types: ["ReactiveFactoryTimeTrialNormalEggRobo"]},
{ name: "Reactive Factory in Time Trial (Normal) with Metal Knuckles", types: ["ReactiveFactoryTimeTrialNormalMetalKnuckles"]},
{ name: "Reactive Factory in Time Trial (Normal) with Metal Sonic", types: ["ReactiveFactoryTimeTrialNormalMetalSonic"]},
{ name: "Reactive Factory in Time Trial (Normal) with Tails Doll", types: ["ReactiveFactoryTimeTrialNormalTailsDoll"]},
{ name: "Reactive Factory in Time Trial (Reverse) with Egg Robo", types: ["ReactiveFactoryTimeTrialReverseEggRobo"]},
{ name: "Reactive Factory in Time Trial (Reverse) with Metal Knuckles", types: ["ReactiveFactoryTimeTrialReverseMetalKnuckles"]},
{ name: "Reactive Factory in Time Trial (Reverse) with Metal Sonic", types: ["ReactiveFactoryTimeTrialReverseMetalSonic"]},
{ name: "Reactive Factory in Time Trial (Reverse) with Tails Doll", types: ["ReactiveFactoryTimeTrialReverseTailsDoll"]},
{ name: "Regal Ruin in Balloon Mode with Egg Robo", types: ["RegalRuinBalloonModeEggRobo"]},
{ name: "Regal Ruin in Balloon Mode with Metal Knuckles", types: ["RegalRuinBalloonModeMetalKnuckles"]},
{ name: "Regal Ruin in Balloon Mode with Metal Sonic", types: ["RegalRuinBalloonModeMetalSonic"]},
{ name: "Regal Ruin in Balloon Mode with Tails Doll", types: ["RegalRuinBalloonModeTailsDoll"]},
{ name: "Regal Ruin in Grand Prix with Egg Robo", types: ["RegalRuinGrandPrixEggRobo"]},
{ name: "Regal Ruin in Grand Prix with Metal Knuckles", types: ["RegalRuinGrandPrixMetalKnuckles"]},
{ name: "Regal Ruin in Grand Prix with Metal Sonic", types: ["RegalRuinGrandPrixMetalSonic"]},
{ name: "Regal Ruin in Grand Prix with Tails Doll", types: ["RegalRuinGrandPrixTailsDoll"]},
{ name: "Regal Ruin in Tag Mode with Egg Robo", types: ["RegalRuinTagModeEggRobo"]},
{ name: "Regal Ruin in Tag Mode with Metal Knuckles", types: ["RegalRuinTagModeMetalKnuckles"]},
{ name: "Regal Ruin in Tag Mode with Metal Sonic", types: ["RegalRuinTagModeMetalSonic"]},
{ name: "Regal Ruin in Tag Mode with Tails Doll", types: ["RegalRuinTagModeTailsDoll"]},
{ name: "Regal Ruin in Time Trial (Normal) with Egg Robo", types: ["RegalRuinTimeTrialNormalEggRobo"]},
{ name: "Regal Ruin in Time Trial (Normal) with Metal Knuckles", types: ["RegalRuinTimeTrialNormalMetalKnuckles"]},
{ name: "Regal Ruin in Time Trial (Normal) with Metal Sonic", types: ["RegalRuinTimeTrialNormalMetalSonic"]},
{ name: "Regal Ruin in Time Trial (Normal) with Tails Doll", types: ["RegalRuinTimeTrialNormalTailsDoll"]},
{ name: "Regal Ruin in Time Trial (Reverse) with Egg Robo", types: ["RegalRuinTimeTrialReverseEggRobo"]},
{ name: "Regal Ruin in Time Trial (Reverse) with Metal Knuckles", types: ["RegalRuinTimeTrialReverseMetalKnuckles"]},
{ name: "Regal Ruin in Time Trial (Reverse) with Metal Sonic", types: ["RegalRuinTimeTrialReverseMetalSonic"]},
{ name: "Regal Ruin in Time Trial (Reverse) with Tails Doll", types: ["RegalRuinTimeTrialReverseTailsDoll"]},
{ name: "Resort Island in Balloon Mode with Egg Robo", types: ["ResortIslandBalloonModeEggRobo"]},
{ name: "Resort Island in Balloon Mode with Metal Knuckles", types: ["ResortIslandBalloonModeMetalKnuckles"]},
{ name: "Resort Island in Balloon Mode with Metal Sonic", types: ["ResortIslandBalloonModeMetalSonic"]},
{ name: "Resort Island in Balloon Mode with Tails Doll", types: ["ResortIslandBalloonModeTailsDoll"]},
{ name: "Resort Island in Grand Prix with Egg Robo", types: ["ResortIslandGrandPrixEggRobo"]},
{ name: "Resort Island in Grand Prix with Metal Knuckles", types: ["ResortIslandGrandPrixMetalKnuckles"]},
{ name: "Resort Island in Grand Prix with Metal Sonic", types: ["ResortIslandGrandPrixMetalSonic"]},
{ name: "Resort Island in Grand Prix with Tails Doll", types: ["ResortIslandGrandPrixTailsDoll"]},
{ name: "Resort Island in Tag Mode with Egg Robo", types: ["ResortIslandTagModeEggRobo"]},
{ name: "Resort Island in Tag Mode with Metal Knuckles", types: ["ResortIslandTagModeMetalKnuckles"]},
{ name: "Resort Island in Tag Mode with Metal Sonic", types: ["ResortIslandTagModeMetalSonic"]},
{ name: "Resort Island in Tag Mode with Tails Doll", types: ["ResortIslandTagModeTailsDoll"]},
{ name: "Resort Island in Time Trial (Normal) with Egg Robo", types: ["ResortIslandTimeTrialNormalEggRobo"]},
{ name: "Resort Island in Time Trial (Normal) with Metal Knuckles", types: ["ResortIslandTimeTrialNormalMetalKnuckles"]},
{ name: "Resort Island in Time Trial (Normal) with Metal Sonic", types: ["ResortIslandTimeTrialNormalMetalSonic"]},
{ name: "Resort Island in Time Trial (Normal) with Tails Doll", types: ["ResortIslandTimeTrialNormalTailsDoll"]},
{ name: "Resort Island in Time Trial (Reverse) with Egg Robo", types: ["ResortIslandTimeTrialReverseEggRobo"]},
{ name: "Resort Island in Time Trial (Reverse) with Metal Knuckles", types: ["ResortIslandTimeTrialReverseMetalKnuckles"]},
{ name: "Resort Island in Time Trial (Reverse) with Metal Sonic", types: ["ResortIslandTimeTrialReverseMetalSonic"]},
{ name: "Resort Island in Time Trial (Reverse) with Tails Doll", types: ["ResortIslandTimeTrialReverseTailsDoll"]}
];

bingoList[2] = mediumChallenges;


var hardChallenges = [
{ name: "Radiant Emerald in Balloon Mode with Amy", types: ["RadiantEmeraldBalloonModeAmy"]},
{ name: "Radiant Emerald in Balloon Mode with Egg Robo", types: ["RadiantEmeraldBalloonModeEggRobo"]},
{ name: "Radiant Emerald in Balloon Mode with Knuckles", types: ["RadiantEmeraldBalloonModeKnuckles"]},
{ name: "Radiant Emerald in Balloon Mode with Metal Knuckles", types: ["RadiantEmeraldBalloonModeMetalKnuckles"]},
{ name: "Radiant Emerald in Balloon Mode with Metal Sonic", types: ["RadiantEmeraldBalloonModeMetalSonic"]},
{ name: "Radiant Emerald in Balloon Mode with Sonic", types: ["RadiantEmeraldBalloonModeSonic"]},
{ name: "Radiant Emerald in Balloon Mode with Super Sonic", types: ["RadiantEmeraldBalloonModeSuperSonic"]},
{ name: "Radiant Emerald in Balloon Mode with Tails", types: ["RadiantEmeraldBalloonModeTails"]},
{ name: "Radiant Emerald in Balloon Mode with Tails Doll", types: ["RadiantEmeraldBalloonModeTailsDoll"]},
{ name: "Radiant Emerald in Grand Prix with Amy", types: ["RadiantEmeraldGrandPrixAmy"]},
{ name: "Radiant Emerald in Grand Prix with Egg Robo", types: ["RadiantEmeraldGrandPrixEggRobo"]},
{ name: "Radiant Emerald in Grand Prix with Knuckles", types: ["RadiantEmeraldGrandPrixKnuckles"]},
{ name: "Radiant Emerald in Grand Prix with Metal Knuckles", types: ["RadiantEmeraldGrandPrixMetalKnuckles"]},
{ name: "Radiant Emerald in Grand Prix with Metal Sonic", types: ["RadiantEmeraldGrandPrixMetalSonic"]},
{ name: "Radiant Emerald in Grand Prix with Sonic", types: ["RadiantEmeraldGrandPrixSonic"]},
{ name: "Radiant Emerald in Grand Prix with Super Sonic", types: ["RadiantEmeraldGrandPrixSuperSonic"]},
{ name: "Radiant Emerald in Grand Prix with Tails", types: ["RadiantEmeraldGrandPrixTails"]},
{ name: "Radiant Emerald in Grand Prix with Tails Doll", types: ["RadiantEmeraldGrandPrixTailsDoll"]},
{ name: "Radiant Emerald in Tag Mode with Amy", types: ["RadiantEmeraldTagModeAmy"]},
{ name: "Radiant Emerald in Tag Mode with Egg Robo", types: ["RadiantEmeraldTagModeEggRobo"]},
{ name: "Radiant Emerald in Tag Mode with Knuckles", types: ["RadiantEmeraldTagModeKnuckles"]},
{ name: "Radiant Emerald in Tag Mode with Metal Knuckles", types: ["RadiantEmeraldTagModeMetalKnuckles"]},
{ name: "Radiant Emerald in Tag Mode with Metal Sonic", types: ["RadiantEmeraldTagModeMetalSonic"]},
{ name: "Radiant Emerald in Tag Mode with Sonic", types: ["RadiantEmeraldTagModeSonic"]},
{ name: "Radiant Emerald in Tag Mode with Super Sonic", types: ["RadiantEmeraldTagModeSuperSonic"]},
{ name: "Radiant Emerald in Tag Mode with Tails", types: ["RadiantEmeraldTagModeTails"]},
{ name: "Radiant Emerald in Tag Mode with Tails Doll", types: ["RadiantEmeraldTagModeTailsDoll"]},
{ name: "Radiant Emerald in Time Trial (Normal) with Amy", types: ["RadiantEmeraldTimeTrialNormalAmy"]},
{ name: "Radiant Emerald in Time Trial (Normal) with Egg Robo", types: ["RadiantEmeraldTimeTrialNormalEggRobo"]},
{ name: "Radiant Emerald in Time Trial (Normal) with Knuckles", types: ["RadiantEmeraldTimeTrialNormalKnuckles"]},
{ name: "Radiant Emerald in Time Trial (Normal) with Metal Knuckles", types: ["RadiantEmeraldTimeTrialNormalMetalKnuckles"]},
{ name: "Radiant Emerald in Time Trial (Normal) with Metal Sonic", types: ["RadiantEmeraldTimeTrialNormalMetalSonic"]},
{ name: "Radiant Emerald in Time Trial (Normal) with Sonic", types: ["RadiantEmeraldTimeTrialNormalSonic"]},
{ name: "Radiant Emerald in Time Trial (Normal) with Super Sonic", types: ["RadiantEmeraldTimeTrialNormalSuperSonic"]},
{ name: "Radiant Emerald in Time Trial (Normal) with Tails", types: ["RadiantEmeraldTimeTrialNormalTails"]},
{ name: "Radiant Emerald in Time Trial (Normal) with Tails Doll", types: ["RadiantEmeraldTimeTrialNormalTailsDoll"]},
{ name: "Radiant Emerald in Time Trial (Reverse) with Amy", types: ["RadiantEmeraldTimeTrialReverseAmy"]},
{ name: "Radiant Emerald in Time Trial (Reverse) with Egg Robo", types: ["RadiantEmeraldTimeTrialReverseEggRobo"]},
{ name: "Radiant Emerald in Time Trial (Reverse) with Knuckles", types: ["RadiantEmeraldTimeTrialReverseKnuckles"]},
{ name: "Radiant Emerald in Time Trial (Reverse) with Metal Knuckles", types: ["RadiantEmeraldTimeTrialReverseMetalKnuckles"]},
{ name: "Radiant Emerald in Time Trial (Reverse) with Metal Sonic", types: ["RadiantEmeraldTimeTrialReverseMetalSonic"]},
{ name: "Radiant Emerald in Time Trial (Reverse) with Sonic", types: ["RadiantEmeraldTimeTrialReverseSonic"]},
{ name: "Radiant Emerald in Time Trial (Reverse) with Super Sonic", types: ["RadiantEmeraldTimeTrialReverseSuperSonic"]},
{ name: "Radiant Emerald in Time Trial (Reverse) with Tails", types: ["RadiantEmeraldTimeTrialReverseTails"]},
{ name: "Radiant Emerald in Time Trial (Reverse) with Tails Doll", types: ["RadiantEmeraldTimeTrialReverseTailsDoll"]},
{ name: "Radical City in Balloon Mode with Super Sonic", types: ["RadicalCityBalloonModeSuperSonic"]},
{ name: "Radical City in Grand Prix with Super Sonic", types: ["RadicalCityGrandPrixSuperSonic"]},
{ name: "Radical City in Tag Mode with Super Sonic", types: ["RadicalCityTagModeSuperSonic"]},
{ name: "Radical City in Time Trial (Normal) with Super Sonic", types: ["RadicalCityTimeTrialNormalSuperSonic"]},
{ name: "Radical City in Time Trial (Reverse) with Super Sonic", types: ["RadicalCityTimeTrialReverseSuperSonic"]},
{ name: "Reactive Factory in Balloon Mode with Super Sonic", types: ["ReactiveFactoryBalloonModeSuperSonic"]},
{ name: "Reactive Factory in Grand Prix with Super Sonic", types: ["ReactiveFactoryGrandPrixSuperSonic"]},
{ name: "Reactive Factory in Tag Mode with Super Sonic", types: ["ReactiveFactoryTagModeSuperSonic"]},
{ name: "Reactive Factory in Time Trial (Normal) with Super Sonic", types: ["ReactiveFactoryTimeTrialNormalSuperSonic"]},
{ name: "Reactive Factory in Time Trial (Reverse) with Super Sonic", types: ["ReactiveFactoryTimeTrialReverseSuperSonic"]},
{ name: "Regal Ruin in Balloon Mode with Super Sonic", types: ["RegalRuinBalloonModeSuperSonic"]},
{ name: "Regal Ruin in Grand Prix with Super Sonic", types: ["RegalRuinGrandPrixSuperSonic"]},
{ name: "Regal Ruin in Tag Mode with Super Sonic", types: ["RegalRuinTagModeSuperSonic"]},
{ name: "Regal Ruin in Time Trial (Normal) with Super Sonic", types: ["RegalRuinTimeTrialNormalSuperSonic"]},
{ name: "Regal Ruin in Time Trial (Reverse) with Super Sonic", types: ["RegalRuinTimeTrialReverseSuperSonic"]},
{ name: "Resort Island in Balloon Mode with Super Sonic", types: ["ResortIslandBalloonModeSuperSonic"]},
{ name: "Resort Island in Grand Prix with Super Sonic", types: ["ResortIslandGrandPrixSuperSonic"]},
{ name: "Resort Island in Tag Mode with Super Sonic", types: ["ResortIslandTagModeSuperSonic"]},
{ name: "Resort Island in Time Trial (Normal) with Super Sonic", types: ["ResortIslandTimeTrialNormalSuperSonic"]},
{ name: "Resort Island in Time Trial (Reverse) with Super Sonic", types: ["ResortIslandTimeTrialReverseSuperSonic"]}
];

bingoList[3] = hardChallenges;


extraHardChallenges = [
{ name: "Radiant Emerald in Balloon Mode with Eggman", types: ["RadiantEmeraldBalloonModeEggman"]},
{ name: "Radiant Emerald in Grand Prix with Eggman", types: ["RadiantEmeraldGrandPrixEggman"]},
{ name: "Radiant Emerald in Tag Mode with Eggman", types: ["RadiantEmeraldTagModeEggman"]},
{ name: "Radiant Emerald in Time Trial (Normal) with Eggman", types: ["RadiantEmeraldTimeTrialNormalEggman"]},
{ name: "Radiant Emerald in Time Trial (Reverse) with Eggman", types: ["RadiantEmeraldTimeTrialReverseEggman"]},
{ name: "Radical City in Balloon Mode with Eggman", types: ["RadicalCityBalloonModeEggman"]},
{ name: "Radical City in Grand Prix with Eggman", types: ["RadicalCityGrandPrixEggman"]},
{ name: "Radical City in Tag Mode with Eggman", types: ["RadicalCityTagModeEggman"]},
{ name: "Radical City in Time Trial (Normal) with Eggman", types: ["RadicalCityTimeTrialNormalEggman"]},
{ name: "Radical City in Time Trial (Reverse) with Eggman", types: ["RadicalCityTimeTrialReverseEggman"]},
{ name: "Reactive Factory in Balloon Mode with Eggman", types: ["ReactiveFactoryBalloonModeEggman"]},
{ name: "Reactive Factory in Grand Prix with Eggman", types: ["ReactiveFactoryGrandPrixEggman"]},
{ name: "Reactive Factory in Tag Mode with Eggman", types: ["ReactiveFactoryTagModeEggman"]},
{ name: "Reactive Factory in Time Trial (Normal) with Eggman", types: ["ReactiveFactoryTimeTrialNormalEggman"]},
{ name: "Reactive Factory in Time Trial (Reverse) with Eggman", types: ["ReactiveFactoryTimeTrialReverseEggman"]},
{ name: "Regal Ruin in Balloon Mode with Eggman", types: ["RegalRuinBalloonModeEggman"]},
{ name: "Regal Ruin in Grand Prix with Eggman", types: ["RegalRuinGrandPrixEggman"]},
{ name: "Regal Ruin in Tag Mode with Eggman", types: ["RegalRuinTagModeEggman"]},
{ name: "Regal Ruin in Time Trial (Normal) with Eggman", types: ["RegalRuinTimeTrialNormalEggman"]},
{ name: "Regal Ruin in Time Trial (Reverse) with Eggman", types: ["RegalRuinTimeTrialReverseEggman"]},
{ name: "Resort Island in Balloon Mode with Eggman", types: ["ResortIslandBalloonModeEggman"]},
{ name: "Resort Island in Grand Prix with Eggman", types: ["ResortIslandGrandPrixEggman"]},
{ name: "Resort Island in Tag Mode with Eggman", types: ["ResortIslandTagModeEggman"]},
{ name: "Resort Island in Time Trial (Normal) with Eggman", types: ["ResortIslandTimeTrialNormalEggman"]},
{ name: "Resort Island in Time Trial (Reverse) with Eggman", types: ["ResortIslandTimeTrialReverseEggman"]}
];

bingoList[4] = extraHardChallenges;