# Generated by Django 5.0.6 on 2025-05-25 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingosync', '0032_auto_20210325_2211'),
        ('bingosync', '0038_alter_game_game_type_value_and_more'),
    ]

    operations = [
    ]
