# Generated by Django 5.0.6 on 2025-05-25 09:56

import bingosync.models.game_type
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingosync', '0039_merge_20250525_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type_value',
            field=models.IntegerField(choices=bingosync.models.game_type.GameType.choices, verbose_name='Game Type'),
        ),
        migrations.AlterField(
            model_name='newcardevent',
            name='game_type_value',
            field=models.IntegerField(choices=bingosync.models.game_type.GameType.choices),
        ),
    ]
